/**
 * ICE - In Case of Emergency
 * Main Server File
 */

require('dotenv').config();
const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const rateLimit = require('express-rate-limit');

// Import routes
const authRoutes      = require('./routes/authRoutes');
const profileRoutes   = require('./routes/profileRoutes');
const emergencyRoutes = require('./routes/emergencyRoutes');
const otpRoutes       = require('./routes/otpRoutes');

// Import middleware
const errorHandler = require('./middleware/errorHandler');

// Initialize Express app
const app = express();
const PORT = process.env.PORT || 3000;

// ── Trust Cloudflare / reverse proxy headers ────────────────────────────────
app.set('trust proxy', 1);

// ── Security middleware ─────────────────────────────────────────────────────
app.use(helmet({
  contentSecurityPolicy: {
    directives: {
      defaultSrc: ["'self'"],
      scriptSrc: [
        "'self'", "'unsafe-inline'",
        "https://cdn.tailwindcss.com",
        "https://cdnjs.cloudflare.com"
      ],
      styleSrc: [
        "'self'", "'unsafe-inline'",
        "https://cdnjs.cloudflare.com",
        "https://fonts.googleapis.com"
      ],
      fontSrc: ["'self'", "https://cdnjs.cloudflare.com", "https://fonts.gstatic.com"],
      imgSrc: ["'self'", "data:", "https:"],
      connectSrc: ["'self'"],
      scriptSrcAttr: ["'unsafe-inline'"]
    }
  }
}));

const allowedOrigins = process.env.ALLOWED_ORIGINS
  ? process.env.ALLOWED_ORIGINS.split(',').map(o => o.trim())
  : null; // null = allow all in development

app.use(cors({
  origin: function(origin, callback) {
    if (!allowedOrigins || !origin || allowedOrigins.includes(origin)) {
      callback(null, true);
    } else {
      callback(new Error('Not allowed by CORS'));
    }
  },
  credentials: true
}));

// ── Body parsing ────────────────────────────────────────────────────────────
app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ extended: true, limit: '1mb' }));

// ── Logging ─────────────────────────────────────────────────────────────────
if (process.env.NODE_ENV !== 'production') {
  app.use(morgan('dev'));
} else {
  app.use(morgan('combined'));
}

// ── Rate limiting ────────────────────────────────────────────────────────────
const emergencyLimiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 100,
  message: 'Too many requests from this IP, please try again later.'
});

const apiLimiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 50,
  message: 'Too many API requests, please try again later.'
});

app.use('/emergency', emergencyLimiter);
app.use('/api', apiLimiter);

// ── Dynamic config.js — injects BASE_URL from server environment ─────────────
// This must come BEFORE express.static so it overrides the static file.
// All HTML pages load /js/config.js, so API_BASE_URL is always the real public URL
// (Cloudflare tunnel, deployed URL, or local IP) — never hardcoded localhost.
app.get('/js/config.js', (req, res) => {
  const baseUrl = (process.env.BASE_URL || `http://localhost:${PORT}`).trim();
  res.setHeader('Content-Type', 'application/javascript');
  res.send(`
// Auto-generated by server — do not edit manually.
// BASE_URL is injected from the server's .env at startup.
const API_BASE_URL = '${baseUrl}';

const API_ENDPOINTS = {
  REGISTER:       API_BASE_URL + '/api/auth/register',
  LOGIN:          API_BASE_URL + '/api/auth/login',
  GET_ME:         API_BASE_URL + '/api/auth/me',
  CREATE_PROFILE: API_BASE_URL + '/api/profile',
  GET_PROFILE:    (id) => API_BASE_URL + '/api/profile/' + id,
  UPDATE_PROFILE: (id) => API_BASE_URL + '/api/profile/' + id,
  GET_EMERGENCY:  (id) => API_BASE_URL + '/emergency/' + id
};
  `.trim());
});

// ── Static files ─────────────────────────────────────────────────────────────
app.use(express.static('.', {
  index: false,
  dotfiles: 'ignore'
}));

// ── Health check ─────────────────────────────────────────────────────────────
app.get('/health', (req, res) => {
  res.status(200).json({
    status: 'OK',
    message: 'ICE Backend is running',
    timestamp: new Date().toISOString()
  });
});

// ── API Routes ────────────────────────────────────────────────────────────────
app.use('/api/auth', authRoutes);
app.use('/api/profile', profileRoutes);
app.use('/api', otpRoutes);
app.use('/emergency', emergencyRoutes);

// ── Frontend entry point ──────────────────────────────────────────────────────
app.get('/', (req, res) => {
  res.sendFile(__dirname + '/index.html');
});

// ── SMS test endpoint (development only) ─────────────────────────────────────
// Visit: http://localhost:3000/test-sms/9876543210
if (process.env.NODE_ENV !== 'production') {
  app.get('/test-sms/:phone', async (req, res) => {
    const { sendSMS } = require('./utils/notifications');
    const phone = req.params.phone;
    console.log(`\n[TEST] Sending test SMS to: ${phone}`);
    const result = await sendSMS(phone, 'ICE App Test: SMS is working correctly!');
    res.json({
      success: result,
      phone,
      twilioSidSet: !!process.env.TWILIO_ACCOUNT_SID,
      twilioFromSet: !!process.env.TWILIO_PHONE_NUMBER,
      twilioSidPreview: process.env.TWILIO_ACCOUNT_SID
        ? process.env.TWILIO_ACCOUNT_SID.slice(0, 8) + '...'
        : 'NOT SET'
    });
  });
}

// ── 404 handler ───────────────────────────────────────────────────────────────
app.use((req, res) => {
  res.status(404).json({ success: false, message: 'Route not found' });
});

// ── Error handling middleware ─────────────────────────────────────────────────
app.use(errorHandler);

// ── MongoDB connection ────────────────────────────────────────────────────────
const connectDB = async () => {
  try {
    const conn = await mongoose.connect(
      process.env.MONGODB_URI || 'mongodb://localhost:27017/ice-db'
    );
    console.log(`✅ MongoDB Connected: ${conn.connection.host}`);
  } catch (error) {
    console.error('❌ MongoDB connection error:', error.message);
    process.exit(1);
  }
};

// ── Start server ──────────────────────────────────────────────────────────────
const startServer = async () => {
  try {
    await connectDB();

    app.listen(PORT, '0.0.0.0', () => {
      const { getLocalIP } = require('./utils/networkUtils');
      const localIP = getLocalIP();

      console.log(`🚀 ICE Backend Server running on port ${PORT}`);
      console.log(`📱 Environment: ${process.env.NODE_ENV || 'development'}`);
      console.log(`🌐 Local access: http://localhost:${PORT}/health`);
      console.log(`📲 Network access: http://${localIP}:${PORT}/health`);
      console.log(`\n💡 For mobile QR code scanning, use: http://${localIP}:${PORT}`);
      console.log(`   Make sure your phone is on the same WiFi network!\n`);
    });
  } catch (error) {
    console.error('❌ Server startup error:', error);
    process.exit(1);
  }
};

process.on('unhandledRejection', (err) => {
  console.error('❌ Unhandled Rejection:', err);
  process.exit(1);
});

startServer();

module.exports = app;
